// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07AjG0yojtIS4RBpO38jThVrMDWlHxNE',
    appId: '1:777037710203:web:499e6421e5a369492473de',
    messagingSenderId: '777037710203',
    projectId: 'moviles-banano',
    authDomain: 'moviles-banano.firebaseapp.com',
    storageBucket: 'moviles-banano.firebasestorage.app',
    measurementId: 'G-J3Q6J67CZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZW9ys0-ZHiwfJ5kl1lTt7mr7voFA_4kI',
    appId: '1:777037710203:android:992f9f370c47384a2473de',
    messagingSenderId: '777037710203',
    projectId: 'moviles-banano',
    storageBucket: 'moviles-banano.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDvTKz92_QbgYGKzMeV33hIp7J5NIKeKs',
    appId: '1:777037710203:ios:b943fbb4572f2d8e2473de',
    messagingSenderId: '777037710203',
    projectId: 'moviles-banano',
    storageBucket: 'moviles-banano.firebasestorage.app',
    iosBundleId: 'com.example.wasaaaaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDvTKz92_QbgYGKzMeV33hIp7J5NIKeKs',
    appId: '1:777037710203:ios:b943fbb4572f2d8e2473de',
    messagingSenderId: '777037710203',
    projectId: 'moviles-banano',
    storageBucket: 'moviles-banano.firebasestorage.app',
    iosBundleId: 'com.example.wasaaaaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA07AjG0yojtIS4RBpO38jThVrMDWlHxNE',
    appId: '1:777037710203:web:b5ddb6d0f329c1e52473de',
    messagingSenderId: '777037710203',
    projectId: 'moviles-banano',
    authDomain: 'moviles-banano.firebaseapp.com',
    storageBucket: 'moviles-banano.firebasestorage.app',
    measurementId: 'G-Y67QNNLRBH',
  );
}
